name: Java CI Pipeline

on:
  push:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Run Tests from Specific Folder
        run: mvn clean test -f login-project1/pom.xml
